const meta = {
  lightFighter: {
    class: "fighter",
    destructible: true,
    speed: 2.5,
    height: 14,
    length: 24,
    points: 100,
  },
  speedComet: {
    class: "comet",
    destructible: false,
    speed: 5,
    height: 22,
    length: 32,
    points: 0,
  },
  comet: {
    class: "comet",
    destructible: false,
    speed: 2.5,
    height: 22,
    length: 32,
    points: 0,
  },
  bannerUP: {
    briefing: true,
    speed: 5,
    length: 1,
    message: `press \u2191 to move UP`
  },
  bannerDOWN: {
    briefing: true,
    speed: 5,
    length: 1,
    message: `press \u2193 to move DOWN`
  },
  bannerSHOOT: {
    briefing: true,
    speed: 5,
    length: 1,
    message: `press space to FIRE`
  },
  rmBanner: {
    briefing: true,
    speed: 5,
    length: 1,
    message: ''
  }
};

export const enemies = [
  { topOffset: 50, leftOffset: 150, type: meta.bannerUP },
  { topOffset: 50, leftOffset: 400, type: meta.rmBanner },
  { topOffset: 100, leftOffset: 450, type: meta.speedComet },
  { topOffset: 150, leftOffset: 500, type: meta.speedComet },
  { topOffset: 220, leftOffset: 510, type: meta.speedComet },
  { topOffset: 250, leftOffset: 550, type: meta.speedComet },
  { topOffset: 350, leftOffset: 570, type: meta.speedComet },
  { topOffset: 200, leftOffset: 600, type: meta.speedComet },
  { topOffset: 320, leftOffset: 650, type: meta.speedComet },
  { topOffset: 50, leftOffset: 1000, type: meta.bannerDOWN },
  { topOffset: 50, leftOffset: 1250, type: meta.rmBanner },
  { topOffset: 40, leftOffset: 1300, type: meta.speedComet },
  { topOffset: 90, leftOffset: 1320, type: meta.speedComet },
  { topOffset: 120, leftOffset: 1350, type: meta.speedComet },
  { topOffset: 160, leftOffset: 1400, type: meta.speedComet },
  { topOffset: 200, leftOffset: 1430, type: meta.speedComet },
  { topOffset: 250, leftOffset: 1480, type: meta.speedComet },
  { topOffset: 270, leftOffset: 1530, type: meta.speedComet },
  { topOffset: 300, leftOffset: 1590, type: meta.speedComet },
  { topOffset: 50, leftOffset: 1850, type: meta.bannerSHOOT },
  { topOffset: 50, leftOffset: 2150, type: meta.rmBanner },
  { topOffset: 120, leftOffset: 1100, dev: -1.5, type: meta.lightFighter },
  { topOffset: 200, leftOffset: 1150, dev: 1.5, type: meta.lightFighter },
  { topOffset: 300, leftOffset: 1200, dev: -0.5, type: meta.lightFighter },
  { topOffset: 80, leftOffset: 1250, dev: -1.0, type: meta.lightFighter },
  { topOffset: 180, leftOffset: 1300, dev: 1.0, type: meta.lightFighter },
  { topOffset: 240, leftOffset: 1350, dev: 1.75, type: meta.lightFighter },
  // { topOffset: 200, leftOffset: 250, type: meta.speedComet },
  // { topOffset: 250, leftOffset: 300, type: meta.speedComet },
  // { topOffset: 300, leftOffset: 320, type: meta.speedComet },
  // { topOffset: 80, leftOffset: 600, type: meta.bannerDOWN },
  // { topOffset: 220, leftOffset: 400, dev: -1.5, type: meta.lightFighter },
  // { topOffset: 260, leftOffset: 500, dev: 0.5, type: meta.lightFighter },
  // { topOffset: 320, leftOffset: 550, dev: 1, type: meta.lightFighter },
  // { topOffset: 180, leftOffset: 600, type: meta.comet },
  // { topOffset: 80, leftOffset: 750, dev: -0.7, type: meta.lightFighter },
  // { topOffset: 280, leftOffset: 900, type: meta.comet },
  // { topOffset: 260, leftOffset: 1000, dev: -0.4, type: meta.lightFighter },
  // { topOffset: 280, leftOffset: 1100, dev: 0.7, type: meta.lightFighter },
  // { topOffset: 100, leftOffset: 1150, type: meta.comet },
  // { topOffset: 300, leftOffset: 1200, type: meta.comet },
  // { topOffset: 80, leftOffset: 1250, dev: 0.8, type: meta.lightFighter },
  // { topOffset: 220, leftOffset: 1450, dev: 1., type: meta.lightFighter },
  // { topOffset: 260, leftOffset: 1500, dev: -1, type: meta.lightFighter },
  // { topOffset: 80, leftOffset: 1600, type: meta.comet },
  // { topOffset: 180, leftOffset: 1650, type: meta.comet },
  // { topOffset: 320, leftOffset: 1800, dev: -0.5, type: meta.lightFighter },
];
